version: '3'
services:
    app:
      container_name: dorayaki-backend
      build: .
      ports: 
        - 8080:8080 
      restart: on-failure
      volumes:
        - api:/usr/src/app/
      depends_on:
        - db
      networks:
        - fullstack
   
    db:
      image: mysql:5.7
      container_name: dorayaki
      ports: 
        - 3306:3306
      environment: 
        - MYSQL_ROOT_HOST=${DB_HOST} 
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_DATABASE=${DB_NAME}
        - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      volumes:
        - database_mysql:/var/lib/mysql
      networks:
        - fullstack
  
volumes:
    api:
    database_mysql:

networks:
    fullstack:
      driver: bridge